# Generated by Django 4.2 on 2023-05-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('DOB', models.DateField(blank=True, max_length=6, null=True)),
                ('mobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('Gender', models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHER ONE')], default=1, max_length=10)),
            ],
        ),
    ]
