# Generated by Django 4.2 on 2023-05-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')], default=1, max_length=10),
        ),
    ]
